### ISSUE TITLE
从没见过这么佛系的乐队

### ISSUE THREAD

**Issue by shanuan** [littleflute/littleflute#1020]
https://www.bilibili.com/video/BV1kV411y7Wo/?spm_id_from=333.788.videocard.6

**Comment by shanuan** [comment]
那个厌世的鼓手又来了，这次更加的喜欢他了
https://www.bilibili.com/video/BV1kb411F7nJ/?spm_id_from=333.788.videocard.0

**Comment by shanuan** [comment]
"Let Her Go" FOUR BROTHERS cover
https://www.youtube.com/watch?v=yTOU27-YBek

**Comment by littleflute** [comment]
https://www.addyoutube.com/watch?v=yTOU27-YBek

**Comment by littleflute** [comment]
https://www.yout.com/watch?v=yTOU27-YBek
